# db/seeds/locations.rb
def create_locations
  puts "creating locations..."

  locations = Location.create!([
    { name: 'Mount Fuji Fujiyoshida 5th Station', city: 'Fujiyoshida', prefecture: 'yamanashi',
      details: 'popular starting point for mount fuji climbs with camping facilities',
      tips: 'best hiking season is july-august',
      warnings: 'altitude sickness possible above 2400m' },
    { name: 'Ogawayama', city: 'Saku', prefecture: 'nagano',
      details: 'premier granite climbing area with multi-pitch routes',
      tips: 'spring and fall offer best climbing conditions',
      warnings: 'some routes require trad gear' },
    { name: 'Mount Takao', city: 'Hachioji', prefecture: 'tokyo',
      details: 'accessible mountain with multiple hiking trails',
      tips: 'trail 6 is least crowded',
      warnings: 'very busy during autumn leaves season' },
    { name: 'Mitake Valley', city: 'Ome', prefecture: 'tokyo',
      details: 'river-side bouldering and top-rope climbing area',
      tips: 'good shade for summer climbing',
      warnings: 'routes can be slippery after rain' },
    { name: 'Nagatoro', city: 'Nagatoro', prefecture: 'saitama',
      details: 'riverside climbing area with camping nearby',
      tips: 'many beginner-friendly routes',
      warnings: 'check river levels during rainy season' },
    { name: 'Lake Kawaguchiko', city: 'Fujikawaguchiko', prefecture: 'yamanashi',
      details: 'lakeside campsites with mt. fuji views',
      tips: 'book ahead for sites with best fuji views',
      warnings: 'high winds common in winter' },
    { name: 'Shiretoko National Park', city: 'Shari', prefecture: 'hokkaido',
      details: 'unspoiled nature and scenic coastlines',
      tips: 'bear warnings in place, bring bells',
      warnings: 'harsh winter conditions' },
    { name: 'Shirakami-Sanchi', city: 'Ajigasawa', prefecture: 'aomori',
      details: 'unesco-listed beech forest trekking area',
      tips: 'great for birdwatching and multi-day treks',
      warnings: 'limited accommodations nearby' },
    { name: 'Hachimantai', city: 'Hachimantai', prefecture: 'iwate',
      details: 'volcanic plateau with hot springs and scenic trails',
      tips: 'best visited in autumn for vibrant foliage',
      warnings: 'snowfall can block trails in winter' },
    { name: 'Zao Mountain Range', city: 'Zao', prefecture: 'miyagi',
      details: 'famous for frost-covered trees and scenic hiking',
      tips: 'visit in winter for "snow monsters" or in summer for hiking',
      warnings: 'cold conditions in winter' },
    { name: 'Mount Chokai', city: 'Nikaho', prefecture: 'akita',
      details: 'stratovolcano with panoramic coastal views',
      tips: 'bring windproof gear due to strong gusts',
      warnings: 'rapid weather changes at summit' },
    { name: 'Mount Gassan', city: 'Tsuruoka', prefecture: 'yamagata',
      details: 'sacred peak with pilgrimage trails',
      tips: 'popular for spiritual hikes in summer',
      warnings: 'deep snow until late spring' },
    { name: 'Oze National Park', city: 'Minamiaizu', prefecture: 'fukushima',
      details: 'expansive highland marshland',
      tips: 'great for summer wildflowers',
      warnings: 'limited access in winter' },
    { name: 'Mount Tsukuba', city: 'Tsukuba', prefecture: 'ibaraki',
      details: 'double-peaked mountain with easy trails',
      tips: 'take the ropeway for scenic views',
      warnings: 'can be crowded on weekends' },
    { name: 'Nikko National Park', city: 'Nikko', prefecture: 'tochigi',
      details: 'unesco-listed park with waterfalls and lakes',
      tips: 'best visited in autumn for fall foliage',
      warnings: 'heavy snowfall in winter' },
    { name: 'Mount Tanigawa', city: 'Minakami', prefecture: 'gunma',
      details: 'rocky mountain with challenging climbs',
      tips: 'take the ropeway for a head start',
      warnings: "one of japan's most dangerous mountains" },
    { name: 'Himeji Castle', city: 'Himeji', prefecture: 'hyogo',
      details: 'historic castle with well-preserved architecture',
      tips: 'visit during off-peak hours to avoid crowds',
      warnings: 'guided tours may be required for detailed exploration' },
    { name: 'Mt. Seppiko', city: 'Himeji', prefecture: 'hyogo',
      details: 'challenging climb near himeji with scenic views',
      tips: 'ensure proper climbing gear and check weather conditions',
      warnings: 'routes can be steep and slippery' }
  ])

  puts "created #{Location.count} locations"
  locations.each { |loc| puts "- #{loc.name}" }
  locations
end
