# db/seeds/locations.rb
def create_locations
  puts "creating locations..."

  locations = Location.create!([
  { name: 'Mount Fuji Fujiyoshida 5th Station', city: 'Fujiyoshida', prefecture: 'Yamanashi',
    details: 'Popular starting point for mount fuji climbs with camping facilities',
    tips: 'Best hiking season is july-august',
    warnings: 'Altitude sickness possible above 2400m' },
  { name: 'Ogawayama', city: 'Saku', prefecture: 'Nagano',
    details: 'Premier granite climbing area with multi-pitch routes',
    tips: 'Spring and fall offer best climbing conditions',
    warnings: 'Some routes require trad gear' },
  { name: 'Mount Takao', city: 'Hachioji', prefecture: 'Tokyo',
    details: 'Accessible mountain with multiple hiking trails',
    tips: 'Trail 6 is least crowded',
    warnings: 'Very busy during autumn leaves season' },
  { name: 'Mitake Valley', city: 'Ome', prefecture: 'Tokyo',
    details: 'River-side bouldering and top-rope climbing area',
    tips: 'Good shade for summer climbing',
    warnings: 'Routes can be slippery after rain' },
  { name: 'Nagatoro', city: 'Nagatoro', prefecture: 'Saitama',
    details: 'Riverside climbing area with camping nearby',
    tips: 'Many beginner-friendly routes',
    warnings: 'Check river levels during rainy season' },
  { name: 'Lake Kawaguchiko', city: 'Fujikawaguchiko', prefecture: 'Yamanashi',
    details: 'Lakeside campsites with mt. fuji views',
    tips: 'Book ahead for sites with best fuji views',
    warnings: 'High winds common in winter' },
  { name: 'Shiretoko National Park', city: 'Shari', prefecture: 'Hokkaido',
    details: 'Unspoiled nature and scenic coastlines',
    tips: 'Bear warnings in place, bring bells',
    warnings: 'Harsh winter conditions' },
  { name: 'Shirakami-Sanchi', city: 'Ajigasawa', prefecture: 'Aomori',
    details: 'Unesco-listed beech forest trekking area',
    tips: 'Great for birdwatching and multi-day treks',
    warnings: 'Limited accommodations nearby' },
  { name: 'Hachimantai', city: 'Hachimantai', prefecture: 'Iwate',
    details: 'Volcanic plateau with hot springs and scenic trails',
    tips: 'Best visited in autumn for vibrant foliage',
    warnings: 'Snowfall can block trails in winter' },
  { name: 'Zao Mountain Range', city: 'Zao', prefecture: 'Miyagi',
    details: 'Famous for frost-covered trees and scenic hiking',
    tips: 'Visit in winter for "snow monsters" or in summer for hiking',
    warnings: 'Cold conditions in winter' },
  { name: 'Mount Chokai', city: 'Nikaho', prefecture: 'Akita',
    details: 'Stratovolcano with panoramic coastal views',
    tips: 'Bring windproof gear due to strong gusts',
    warnings: 'Rapid weather changes at summit' },
  { name: 'Mount Gassan', city: 'Tsuruoka', prefecture: 'Yamagata',
    details: 'Sacred peak with pilgrimage trails',
    tips: 'Popular for spiritual hikes in summer',
    warnings: 'Deep snow until late spring' },
  { name: 'Oze National Park', city: 'Minamiaizu', prefecture: 'Fukushima',
    details: 'Expansive highland marshland',
    tips: 'Great for summer wildflowers',
    warnings: 'Limited access in winter' },
  { name: 'Mount Tsukuba', city: 'Tsukuba', prefecture: 'Ibaraki',
    details: 'Double-peaked mountain with easy trails',
    tips: 'Take the ropeway for scenic views',
    warnings: 'Can be crowded on weekends' },
  { name: 'Nikko National Park', city: 'Nikko', prefecture: 'Tochigi',
    details: 'Unesco-listed park with waterfalls and lakes',
    tips: 'Best visited in autumn for fall foliage',
    warnings: 'Heavy snowfall in winter' },
  { name: 'Mount Tanigawa', city: 'Minakami', prefecture: 'Gunma',
    details: 'Rocky mountain with challenging climbs',
    tips: 'Take the ropeway for a head start',
    warnings: "One of japan's most dangerous mountains" },
  { name: 'Himeji Castle', city: 'Himeji', prefecture: 'Hyogo',
    details: 'Historic castle with well-preserved architecture',
    tips: 'Visit during off-peak hours to avoid crowds',
    warnings: 'Guided tours may be required for detailed exploration' },
  { name: 'Mt. Seppiko', city: 'Himeji', prefecture: 'Hyogo',
    details: 'Challenging climb near himeji with scenic views',
    tips: 'Ensure proper climbing gear and check weather conditions',
    warnings: 'Routes can be steep and slippery' }
])

  puts "created #{Location.count} locations"
  locations.each { |loc| puts "- #{loc.name}" }
  locations
end
